### ISSUE TITLE
HTML tags on inbound OTR encrypted messages should not be displayed

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#104]

**Comment by pmembrey** [comment]
I don't suppose a bounty would help get this fixed? :)

**Comment by aelmahmoudy** [comment]
@pmembrey hah, I worked on one issue that had a bounty, yet I never got that bounty !

**Comment by aelmahmoudy** [comment]
Does this only happen when the other chat party is using Pidgin ?

**Comment by pmembrey** [comment]
The other party is using Adium, but as far as I know, it's based on the same underlying libraries so it could be the same issue.

**Comment by aelmahmoudy** [comment]
Ok, I just did some tests with a Pidgin client. I found the following:
* If I send formatted text  (bold or colored text for example) using Pidgin in an un-encrypted session, Xabber receives clear text without any HTML tags
* If I send unformatted (plain) text using Pidgin in an OTR session, Xabber will still receive clear text without HTML tags
* If I send formatted text using Pidgin in an OTR session, Xabber will get HTML tags.

So my conclusion is that Xabber is probably capable of stripping the HTML tags (since it obviously did so in the first case), it just seems to be some call that needs to be done in the case of receiving OTR messages.

**Comment by pmembrey** [comment]
I came across this on the way home. It might have some useful info:

http://bugs.bitlbee.org/bitlbee/ticket/690

**Comment by aelmahmoudy** [comment]
Sorry, I just enabled Pidgin's XMPP console, I found that, as [https://developer.pidgin.im/ticket/8453 Pidgin ticket] says, Pidgin doesn't send any HTML tags in case of un-encrypted session.

So probably it is either a problem in Pidgin or Pidgin's OTR plugin.

**Comment by aelmahmoudy** [comment]
Re-opened by this commit: https://github.com/redsolution/xabber-android/commit/7ec1518c812945c28529135e754c15da032feef1

**Comment by enachi** [comment]
Having private OpenFire server and only OTR sessions by default show all the HTML tags, which is so annoying. xabber 2.0.2(360)

**Comment by andrewnenakhov** [comment]
@Str4tocaster check it out please. Maybe with @oxoWrk

**Comment by enachi** [comment]
I forgot to mention that the HTML tags I see, coming from Adium client for OS X. Thanks for reopening this.

**Comment by oxoWrk** [comment]
[XEP-0071](https://xmpp.org/extensions/xep-0071.html#concepts) say:
`
In Jabber/XMPP communications, the meaning (as opposed to markup) of the message MUST always be represented as best as possible in the normal <body/> child element or elements of the <message/> stanza qualified by the 'jabber:client' (or 'jabber:server') namespace. Lightweight text markup is then provided within an <html/> element qualified by the 'http://jabber.org/protocol/xhtml-im' namespace. [16] However, this <html/> element is used solely as a "wrapper" for the XHTML content itself, which content is encapsulated via one or more <body/> elements qualified by the 'http://www.w3.org/1999/xhtml' namespace, along with appropriate child elements thereof.`

 Pidgin in an OTR session puts  formatted text inside  body tag. Xabber, as it should, displays the contents of the body tag
