### ISSUE TITLE
xabber tries to validate tls-certificate against the user's servername instead of validation against the actual server host.

### ISSUE THREAD

**Issue by PaulKlumpp** [redsolution/xabber-android#204]
Multi-Federation servers do serve multiple virtual hosts on the same host - which results in TLS-certificate validation error on connection.

Example; The host xmpp.lala.com may serve for the user "wooo" @ "lala.com" and "waa" @ "lolo.com".

On connection, the server lala.com has a certificate valid for *.lala.com and lala.com.
Xabber will throw a validation error when user "waa" @ "lolo.com" connects to the xmpp.lala.com host. This seems wrong. 

Xabber should see:
The actual xmpp-host for waa@lolo.com is at xmpp.lala.com - so the certificate is to be validated against xmpp.lala.com

**Comment by merijn** [comment]
This problem is stopping me from using Xabber with my jabber hosting at Fastmail, I've tried both the latest Xabber and the latest Xabber Beta, but neither will succesfully connect and neither allow me to force it to accept the certificate...

**Comment by merijn** [comment]
I dove into the codebase and it turns out the fix was fairly easy, see pull request #451

I would love if this could be merged soon, because Xabber is by far the most pleasant client I've used on Android, however it is currently unusable for me.

**Comment by alexte** [comment]
I thought the same. (the hostname should be used and not the domain)
But RFC3920 states very clear that it should be done the other way (before the patch).
Read on: http://xmpp.org/rfcs/rfc3920.html#tls Rule 8.

The solution for merijn is to use SAN certs like from go daddy who allways include Hostname + Domainname as SAN. My patch from 2 weeks ago fixed the SAN handling.

**Comment by merijn** [comment]
@alexte SAN is not a solution for me as I do not have any control over the server or it's certificates. I'm ok with keeping the original behaviour provided we can get an override switch to enable the behaviour of this patch.

As is, trying to connect with Xabber to the FastMail server the connection silently fails on the SSL cert, disabling SSL validation pops up a prompt that says the jabber host and server don't match, but I have no way to say "Yes, I know, continue connecting anyway".

So I really want a way to tell Xabber that it should really just accept the "chat.messagingengine.com" cert from FastMail instead of giving me no way to overwrite the cert and connect.

Also, whoever came up with that RFC is an idiot, it renders setups like this where a third-party hosts your jabber completely impossible...

**Comment by alexte** [comment]
I agree, the rfc seems wrong to me too, but leaving the standard may break other setups that are configured to the standard.
You may disable "check server cert" in "settings - security"  as a workaround.

**Comment by alexte** [comment]
the newer xmpp rfc still takes the domain for cert validation and suggest SNI mechanisms for cert selection. if I understand it right.

**Comment by merijn** [comment]
Disabling "check server cert" is not a workaround.

I've tried both Xabber and Xabber beta in multiple possible permutations of settings and I cannot make it connect.

If I check "Check server cert" I get a notification for the wrong certificate and the question whether I want to ignore this cert. If I click "ok" (or cancel, doesn't matter) it gives up trying to connect.

If I uncheck "Check server cert" Xabber just goes in a loop trying to connect, producing a "connection error", and then back to trying to connect.

I haven't found a way to basically tell it "shut up, I know, just connect!"

**Comment by lars-becker** [comment]
Hmm I find the XMPP specification somewhat ambiguous. But if you read it like above the specification should be interpreted in a more liberal way, since this interpretation makes delegation more difficult. 

One reason why we have SRV records in the DNS is to delegate services to another system. It's difficult to delegate a service if the service provider (for example B) has to acquire certificates from all domain holders (for example A and C) who want to delegate a service. It doesn't make much sense from a security and economical standpoint if A and C delegate xmpp services to B and they regularly have to obtain new certificates and give them to B... Since B provides the service he should be responsible for acquiring a server certificate for the server which actually provides the service.  This would be analogous to mail services also.. The organization Z might have the domain example.org but have a provider Y which has servers in the domain example.com. There is a mx record in the domain example.org which delegates the service to example.com.  When connecting to the mail exchanger clients actually check for the server certificate of the mx...  If one adheres to the policy outlined above we will have a lot of security warnings to a lot of users who will develop a habit to click such warnings away; especially since the advent of short living certificates of let's encrypt.

**Comment by andrewnenakhov** [comment]
Not ambiguous. Client should check certificate of an XMPP server it connects, not of a physical server it connects to. You can specify custom host by IP, are you going to issue a certificate for 192.168.1.1 ? 

Currently Xabber works correctly with certificates, issue is no longer relevant.
