### ISSUE TITLE
Option to choose contact's resource to chat with

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#22]

**Comment by wheeskers** [comment]
Hi Team, is there a chance that this feature will be implemented?
It's very handy when someone logged in from multiple devices. Just asking though.

**Comment by neoretix** [comment]
Please, implement this feature. It's very important for me.

**Comment by pyhedgehog** [comment]
+1

**Comment by neoretix** [comment]
Maybe I can donate for this option to be implemeted??? I have troubles with resources everyday because I can't choose recipient's resource to send message.

**Comment by matrixx740** [comment]
Partial cause of bug 365https://github.com/redsolution/xabber-android/issues/365

**Comment by plastikat** [comment]
+1

**Comment by andrewnenakhov** [comment]
Goes against our philosophy for Xabber

**Comment by wheeskers** [comment]
@andrewnenakhov 

Goes against Xabber philosophy? Resource concept is a part of core XMPP features so stating "Xabber is designed to be the best Jabber client for Android" on the project front page and ditching resources is rather strange.

I'm not trying to demand anything but comments clearly show this feature is really necessary for users with multiple resources, leaving issue open would help attract someone with enough knowledge to implement this.

**Comment by andrewnenakhov** [comment]
@wheeskers (geeky) users who need that functionality can choose from a variety of clients out there.

We're aiming to create an app that 'just works' for regular forks, and all these concepts of priorities, resources and other stuff are clearly obsolete by now. It's just a bad idea from 1999 that does not fit well in current environment where users want convergence and continue chat from any device they currently have at hand: desktop computer, tablet, smartphone, etc. Having option to talk to specific resources is clearly harmful for this way of using Xabber.

**Comment by plastikat** [comment]
@andrewnenakhov

What you are saying is so much aligned with contemporary (unfortunately, widespread) software design trends, which I personally strongly dislike. In the past, software used to be highly configurable and customizable; nowadays it gradually becomes less and less so. It is now a common practice to decide *for* end users what they need and then present them with minimum options so that they cannot change it much.

I am too not trying to demand anything, just saying people missing this feature are *real* people too, even though there are not too many of them. As for non-geek users, you can always hide and disable advanced features to avoid overwhelming them; I am sure others don't mind to dig a bit to enable something advanced.

**Comment by andrewnenakhov** [comment]
@plastikat the idea of priorities and resources originated when disk space costs were more that 1000x more than it costs now, so server's job was to route incoming messages in some direction and to not store anything. Since that time, everything changed. Practice showed that everyone but the geekiest customers just can not grasp this concept, and if we'll complicate interface for the sake of 0.1% of users who manage to get some good of this functionality, we'll be spending more that 2x efforts to serve these 0.1%. Also, our resources for app development and maintenance are far from infinite. 

So for now our priorities are to provide regular users with first class chat experience before XMPP goes extinct as an obsolete protocol that isn't used by anyone but junkies and some hardcore bearded guys in their 50s. 

Hope you understand.
