### ISSUE TITLE
Back button to close a chat

### ISSUE THREAD

**Issue by giner** [redsolution/xabber-android#223]
If I get a message from somebody and I wa't to close the chat I have to press "menu" and then "close chat". This is a frequent operation and would be really nice to be able to close chat easier. I would prefer using "back" button for this. Is it possible to add such an option to the settings?

**Comment by andrewnenakhov** [comment]
No, back button should not be used to close active chat.

**Comment by giner** [comment]
The problem in this behavior is that if you don't close active chat then it is not clear if you have new messages coming from contacts with opened chats or not. It looks like you always have new messages. That is why I'm asking for easy way to close active chat. This is not necessarily should be back button, this can be close button on the window itself and this can be optional and configured in settings.

**Comment by andrewnenakhov** [comment]
#336 should do, I guess.

**Comment by alanthehat** [comment]
Would a 'new messages' flag on the list of chats be a better solution?
Possibly with an option to sort the list by latest interaction? (Although this would have to be slow as 2 or more chats in use would be bouncing around too much) 
I don't like the idea of the [back] button closing a chat, but a swipe left on the list of open chats is an expected way of closing them, at least since android 4
Also [long-press]...[close]
