### ISSUE TITLE
Security threat: accounts' passwords are stored in clear text !

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#276]
Passwords can be found out if someone opens the xabber.db file using sqlite and running a simple SQL query on 'accounts' table.

Please store the passwords in some crypted form. 
Thanks

**Comment by andrewnenakhov** [comment]
One can't normally access those files on non-rooted Android devices, and other apps can't access that data at all. No security issue here.

Btw, if apps keeps some encrypted data it must have means to decrypt it in order to use them (for example to connect to XMPP server). Then any user who has access  to app data would have means to decrypt them as well.

**Comment by Magissia** [comment]
And what prevent one to make a malicious software exploiting a security flaw to obtain root ? Don't trust the system if you want something secure.

----- Reply message -----
De : "Andrew Nenakhov" <notifications@github.com>
Pour : "redsolution/xabber-android" <xabber-android@noreply.github.com>
Cc : "Magissia" <nolododo@hotmail.com>
Objet : [xabber-android] Security threat: accounts' passwords are stored in clear text ! (#276)
Date : ven., janv. 30, 2015 17:10


One can't normally access those files on non-rooted Android devices, and other apps can't access that data at all. No security issue here.

Btw, if apps keeps some encrypted data it must have means to decrypt it in order to use them (for example to connect to XMPP server). Then any user who has access  to app data would have means to decrypt them as well.

---

**Comment by nodiscc** [comment]
@Magissia if some malware gets root access you are pwned anyway. It can listen to your keystrokes, extract passwords from RAM and whatever you can imagine. If you don't trust the system then don't provide your passwords.
