### ISSUE TITLE
version numbers - when is version 1?

### ISSUE THREAD

**Issue by alanthehat** [redsolution/xabber-android#354]
Having used this software for quite a while I feel that it should be dignified with a 'released' style version number. 
For me '0.n' version numbers look like beta-test versions & anywhere other than Android I would give them no trust. 
The version that I am using (0.9.30b) is, I feel, worthy of being called a 'release' version & being given a version number of at least 1.0 

There's a few niggles left, but they can be dealt with in v1.0.1

**Comment by ironjan** [comment]
The issues for the 1.0 release are found [via the issue tracker](https://github.com/redsolution/xabber-android/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0).

Nonetheless there are [other milestones](https://github.com/redsolution/xabber-android/milestones) to do before the 1.0 release.

**Comment by andrewnenakhov** [comment]
We always intended to call v.1.0 version with full end-to-end XMPP functionality, including in-band registration and changing user avatar. Thanks to work by @aelmahmoudy ( https://github.com/redsolution/xabber-android/pull/339 ) we're now closer to that goal. But version numbering is a very arbitrary thing, so that's no really big deal. Hope this answer to clarify things a bit.
