### ISSUE TITLE
Button to insert smile while typing message

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#42]

**Comment by moshpirit** [comment]
Most of the MI have an emoji pack with a lot of emojis. Since AFIAK AOSP only include emojis using Google software and we're fighting for a free software community and everybody is familiarized with the Telegram emoji pack (also used on Whatsapp), we could include it on Xabber as well (the Telegram app uses a GPL3 license) but it's just my opinion, we can create a different set of emojis too.

The thing is: I think that it would be much used than the encryption launcher, so it should be in a better position, and in my view, the lock icon should be in the top bar or even included in the menu in order to use this space to the emojis.

**Comment by andrewnenakhov** [comment]
Implemented in 2.0.
