### ISSUE TITLE
Customizable Emoticons

### ISSUE THREAD

**Issue by DasNaCl** [redsolution/xabber-android#429]
I discovered that there exists a strong wish of having dozens of emoticons and having the possibility of choosing them on a keyboard. Since save, customizable and attractive (!) communication should be tempting for everyone I suggest to make someone able to add emoticons they like and to make him or her able to choose those and the standard ones on a keyboard.
I discovered this especially in my and in other circles of acquaintances, since they didn't or don't want to use Xabber just because of this - ridiculous.

**Comment by andrewnenakhov** [comment]
Emoticons are a bad idea since when you replace some text characters with graphical image you can't be sure what it'll look like on the far end of conversation. Unified character display is possible only if someone controls all client software, like, say, facebook. So unless someone would be willing to make an internationally recognized standard for emoticons, wasting time to add just one more set of emoticons that are likeed by particular user is pointless. There always will be one more, and all your creative use of custom emoticons could look very different on a far side of conversation.
