### ISSUE TITLE
Slow/crawl on lolipop

### ISSUE THREAD

**Issue by belldandu** [redsolution/xabber-android#482]
So ever since the update to lolipop on verizon's samsung galaxy s 5  this application has been causing my phone to slow down and even crawl.

When trying to use the application it gets worse.
- [ ] Make application compatible with lolipop update on android.

@grigoryfedorov @a-iv @aelmahmoudy @liotier @lizardlab @vkotovv @Semenchikus @joschi @isotherm @merijn @alexte @daviessm

If there is a way to provide debug logs for this application please tell me how and i will do so.

Btw uninstalling this application solves my speed problems ;P but seriously i'd like to be able to use it.

**Comment by moshpirit** [comment]
Maybe could be caused by a huge history or maybe because you installed the app on the SD card.

BTW, I'm not a developer.

**Comment by kamijoutouma** [comment]
Don't have this app installed on SD card. I also don't have a huge history.

Also i know your not a dev which is why i didn't @ you

**Comment by lizardlab** [comment]
I'm not a part of the dev team either... I just contributed a couple lines of XML to fix their issue with port numbers bringing up a full keyboard rather than the numeric one.

Also you're probably going to have to install Android Studio and use this [guide](https://developer.android.com/tools/debugging/index.html) to get the debug logs. I've dabbled in Android development, but I really can't help here :(

**Comment by andrewnenakhov** [comment]
Most likely this issue is no longer relevant.
