### ISSUE TITLE
File Transfer is not working

### ISSUE THREAD

**Issue by ghost** [redsolution/xabber-android#531]
File Transfer is not working

**Comment by moshpirit** [comment]
What version of Xabber are you using?

**Comment by vivekebics** [comment]
I have checked Xabber Beta..There is no file transfer option.Please add the file transfer code

**Comment by vivekebics** [comment]
I am working on xabber-android-1.0.39

**Comment by aileronajay** [comment]
Can you please post the log/exceptions that you are encountering

**Comment by moshpirit** [comment]
AFAIK Xabber 1.0.39 version can't send or receive files and there's 3 weeks without any news so there's no way that you could send or receive files since the apk that we could get compiling directly from Github is the same apk that we get downloading the 1.0.39 version of Xabber from F-droid or Google Play.

**Comment by vivekebics** [comment]
Thank You Very Much

**Comment by andrewnenakhov** [comment]
Current Xabber sends files with HTTP-upload
