### ISSUE TITLE
Can't receive messages sent while I'm not connected

### ISSUE THREAD

**Issue by monnier** [redsolution/xabber-android#613]
When a contact is offline, Xabber tells me in the chat window "The recipient is offline.  Messages you send will be delivered when they come back online".

I haven't checked if it works for those contacts, but in the opposite direction (i.e. when _they_ send me a message while I'm offline) it does not work for me.

Here's for example one thing I've tried:
- on my android device running Xabber (connected to account monnier@member.fsf.org), I switch the Wifi off so I'm not connected any more.
- from some other machine and other account (monnier@jabber.org) I send a message to the monnier@member.fsf.org.
- I enable the Wifi on the Xabber device again.  The device reconnects to member.fsf.org, but the message never shows up.

**Comment by casperklein** [comment]
Try to proper exist Xabber or disconnect your account before turning off wifi. If that works, it can probably be fixed by stream management (xep-0198) which is available in xabbers devolopment build (not yet available at google play).

Background: if you just turn off your wifi, member.fsf.org still thinks that you are connected and messages to you go to nirvana.

**Comment by monnier** [comment]
Hmm... indeed, if I exit Xabber, then send a message, then restart Xabber, the message is received at that point.  Any idea how soon the xep-0198 support will hit F-Droid?

**Comment by casperklein** [comment]
Nope.

**Comment by andrewnenakhov** [comment]
Stream management is supported now.
