### ISSUE TITLE
Xabber and unneeded wifi battery usage

### ISSUE THREAD

**Issue by dveeden** [redsolution/xabber-android#631]
With no accounts connected it should not keep wifi awake even this is enabled in the menu because this is not needed and uses quite some battery capacity.

**Comment by casperklein** [comment]
Do you mean enabled or connected? If you mean the second one as you wrote, think about the following: your device could be connected to a wifi network but the internet gateway is down, so your account is not connected, because the jabber server on the internet could not be reached. Then in my opinion, xabber should keep the wifi connection alive, to periodically retry to connect.

**Comment by dveeden** [comment]
I meant disabled and disconnected.

**Comment by casperklein** [comment]
I understand. If that is a big issue to you, you could close the xabber app, after you disabled all accounts.
