### ISSUE TITLE
A dns lookup should be performed on every reconnect

### ISSUE THREAD

**Issue by staples1347** [redsolution/xabber-android#639]
At the moment, it seems like Xabber only does a dns lookup for the server at program startup.  It should perhaps do this on every reconnect instead as sometimes there might be dns load balancing or when moving from an internal network to an external network (wifi to mobile) or to another site the server ip address in dns might change.

I'm using Xabber 1.0.30

**Comment by andrewnenakhov** [comment]
That would also slow down reconnection by quite some time. Some providers have slooow dns servers, some just can't resolve srv records for some reason. Lot's of issues. We are aware of reconnection issues with dns and looking to provide best practice. Closing this issue, but rest assured this problem is under our constant attention.
