### ISSUE TITLE
Dex cannot parse version 52 byte code.

### ISSUE THREAD

**Issue by obabichev** [redsolution/xabber-android#664]
Log:
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

We have problem to build it in Android studio 2.
Maybe somebody has already solved it, but I can't find solution among issues(

**Comment by casperklein** [comment]
I run into the same issue. Add these lines to build.gradle file in the otr4j project:

    targetCompatibility = '1.7'
    sourceCompatibility = '1.7'

**Comment by audovoice** [comment]
This note should probably be added to the read me because there does not seem to be any other way to get the active branch to work with the newest android studio. It is not immediately obvious how the target compatibility should be added and to what. This is especially true because 
compileJava {
    sourceCompatibility JavaVersion.VERSION_1_7.toString()
    targetCompatibility JavaVersion.VERSION_1_7.toString()
}
did not work for me when it should, at least according to this stack overflow on the subject.
http://stackoverflow.com/questions/33297432/could-not-find-method-sourcecompatibility-for-arguments-on-root-project 

As far as I can tell the branches of this project do not run on the newest version of Android studio without some kind of tweaking. feature/smack_4.2 is the only one I have actually gotten to work after many hours of trying over many frustrated days.

**Comment by andrewnenakhov** [comment]
@Str4tocaster take a look at this

**Comment by Str4tocaster** [comment]
On today Xabber is successful building in latest Android Studio 2.3.2.
