### ISSUE TITLE
Notification for offline messages in conferences

### ISSUE THREAD

**Issue by schlagi123** [redsolution/xabber-android#668]
In the app I set up, that I get notifications on new messages in chats and conferences. But when I am offline and reconnect, I do not get an notification of new messages in a conference (for normal chats i get a notification).

Device:
Blackberry DTEK 50
Androud 6.0.1

**Comment by andrewnenakhov** [comment]
Because some clever people who invented conferences for XMPP somehow thought it's a great idea that you don't get messages when you are offline. When you go online you reconnect to conference every time. In other words, from what I get from your question, conferences work as (poorly as) they are designed.
