### ISSUE TITLE
MUC vanish from list after a while

### ISSUE THREAD

**Issue by casperklein** [redsolution/xabber-android#752]
Version; Xabber 2.0.2 (369)

I can join prosody@conference.prosody.im. But after a while, the MUC vanish from my contact list.

Xabber debug log: https://pastebin.com/raw/Npqxi3RN

> 2017-07-30_22-11-50 D/com.xabber.android.data.message.MessageManager@3439648﹕ removeChat prosody@conference.prosody.im

> 2017-07-30_22-12-20 D/com.xabber.android.data.extension.bookmarks.BookmarksManager@8e07925﹕  Conference prosody@conference.prosody.im was deleted from phone

That was not an issue for me in previous versions  (but I don't know, when this exactly started).

**Comment by andrewnenakhov** [comment]
Xabber now uses bookmarks to track MUCs, if a certain record is set, it treats that all 'connected' conferences should be listed in bookmarks. However, if server or other clients clear those bookmarks for conferences, Xabber will remove them from contact list. @casperklein , please check what happens to your bookmarks to help us what's going on with your conferences.

(Actually I'm totally outraged at MUC in XMPP, idea not to have them in roster is very, very, very bad, it's broken by design. Maybe it was OK in 1999 but not in 2017)

**Comment by casperklein** [comment]
How can I access/see the bookmark list? Or do you mean the contact list?

When I first connect to the MUC, I see the MUC in the contact list among my other contacts. Some time later the MUC vanish there.

**Comment by andrewnenakhov** [comment]
@casperklein it's right in the account settings, below message archive settings )

**Comment by casperklein** [comment]
So.. unfortunately it took a while to happen again, but yesterday it did.

Full debug log from yesterday: https://gist.github.com/casperklein/4ca2395795316aa9b1700bcb647dc94b
For the completeness: MUC that vanish is prosody@conference.prosody.im

@andrewnenakhov I checked the bookmarks as you suggested:

When the MUC is present in my contact list, its also listed in the bookmarks
After the MUC vanish from my contact list, it also vanish from the bookmarks.

**Comment by andrewnenakhov** [comment]
Most likely some other client or maybe server clears bookmarks, and subsequently Xabber removes conferences. This is not too important anyway, our brand new group chat solution is almost ready to roll out.
