### ISSUE TITLE
Please remove Facebook and Google trackers

### ISSUE THREAD

**Issue by linkmauve** [redsolution/xabber-android#802]
As reported by Exodus Privacy, Xabber embeds the code of at least four trackers, three from Facebook and one from Google, see https://reports.exodus-privacy.eu.org/reports/260/

This doesn’t necessarily mean that it is using them, but it would feel a lot safer if you didn’t include them at all, both for our privacy and our contacts’.

**Comment by andrewnenakhov** [comment]
This is not trackers.

**Comment by linkmauve** [comment]
There are four trackers, embedded in the code.  If you are not aware of using them anywhere, please audit the frameworks you are using, maybe they are doing it behind your back.

**Comment by andrewnenakhov** [comment]
Security freaks never cease to amaze me - they use Xabber on Android (by Google) installing it from Google play, which is by definition a tracker of everything they do, yet they run around and bother various projects to "remove" something, and lull themselves with a false sense of security.

Xabber of F-droid does not use libs from Google or Facebook. Now, stop shitposting non-issues here, please. Thank you.

**Comment by linkmauve** [comment]
I don’t personally use Android, this is for your own users and for my contacts who are using your application that I’m opening this issue.

Also, why are you including trackers in the Play Store version, while your client works properly on F-Droid without them?

**Comment by andrewnenakhov** [comment]
Because we have a social sign in feature for normal users to quickly sign into application. Using it requires libs by Google / Facebook that are open source and do precisely what they should: allow social login, it's not a tracker,as I said. 

However, we DO use Crashlytics lib that is totally a tracker and reports us anonymized bugs and crashes in real-time for Google play users, because why not, it makes our life easier developing great stuff, and users of Google Play are so stuffed with personalised trackers that one more anonymized one isn't really a big issue anyway.

**Comment by linkmauve** [comment]
Thanks for your comment, this indeed sounds useful and shouldn’t be an issue as long as you make sure people who don’t want to log in with facebook don’t execute any code from their tracker.

I have reported the missing Crashlytics library to Exodus Privacy, and they told me it’s a known false negative, this should be fixed in a future version. Thanks!
