### ISSUE TITLE
Send files

### ISSUE THREAD

**Issue by rsanjuan87** [redsolution/xabber-android#832]
Xabber says that my jabber server not allow send files but I log in to my account with pidgin on desktop and it's allow send files
So I think it's a bug of app

**Comment by andrewnenakhov** [comment]
Using pidgin as a metric is probably not the best idea. Xabber supports sending files with XEP-0363 HTTP File upload. If it's listed in server capabilities, it works. 

One known issue is that when the account is just added to Xabber, app is busy loading history/avatars/etc, it might process capabilities stanza with a significant delay (a few minutes) during which Xabber will incorrectly tell that 'server does not support sending files/

**Comment by heideline** [comment]
Sorry I connot understand your problems.I'm not a member to Github.I have no account on Xabber, that was the beginneng of our misunderstandings, because I dont't know, what a MPPM account or so  a thing is and I began my search, landing on your side.What must  I do?
I have decided in the meantime, Xabber to deinstall from my tablet, which was installed from my daughter without ending the login-dates or what you say to this. Xabber she want to  deinstall from my tablet, because this App is to difficult; we had find another. Now I find  Xabber not on my tablet, only as a sign like an electric bulb, but it is not under my Apps to deinstall it. I send my daughler an Email to come as soon as possible. Perhaps she is understanding what you mean.O man, why do you can't say it in Russian, my first language for forty years and more. ☹H. Hemmelrath

Von Samsung-Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: Andrew Nenakhov <notifications@github.com> Datum: 11.06.18  20:38  (GMT+01:00) An: redsolution/xabber-android <xabber-android@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [redsolution/xabber-android] Send files (#832) 
Using pidgin as a metric is probably not the best idea. Xabber supports sending files with XEP-0363 HTTP File upload. If it's listed in server capabilities, it works.
One known issue is that when the account is just added to Xabber, app is busy loading history/avatars/etc, it might process capabilities stanza with a significant delay (a few minutes) during which Xabber will incorrectly tell that 'server does not support sending files/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/redsolution/xabber-android/issues/832#issuecomment-396343430","url":"https://github.com/redsolution/xabber-android/issues/832#issuecomment-396343430","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/redsolution/xabber-android","title":"redsolution/xabber-android","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/redsolution/xabber-android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@andrewnenakhov in #832: Using pidgin as a metric is probably not the best idea. Xabber supports sending files with XEP-0363 HTTP File upload. If it's listed in server capabilities, it works. \r\n\r\nOne known issue is that when the account is just added to Xabber, app is busy loading history/avatars/etc, it might process capabilities stanza with a significant delay (a few minutes) during which Xabber will incorrectly tell that 'server does not support sending files/"}],"action":{"name":"View Issue","url":"https://github.com/redsolution/xabber-android/issues/832#issuecomment-396343430"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [redsolution/xabber-android] Send files (#832)",
"sections": [
{
"text": "",
"activityTitle": "**Andrew Nenakhov**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@andrewnenakhov",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"redsolution/xabber-android\",\n\"issueId\": 832,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/redsolution/xabber-android/issues/832#issuecomment-396343430"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344693960\n}"
}
],
"themeColor": "26292E"
}

**Comment by andrewnenakhov** [comment]
@heideline могу и по-русски. Вы как-то не очень правильно используете GitHub. Это ресурс для разработчиков, который рассылает уведомления о разных задачах, которые ставят некоторые продвинутые пользователи. Не совсем понятно, почему Вам приходят уведомления с него, но, думаю, что надо просто найти способ от них отписаться. 

(Насколько я понял, Вам приходят оповещения, а Вы просто нажимаете на них кнопку "ответить" и весь ответ с хвостом из разных служебных данных попадает в трекер задач. Лучше этого не делать. Если у Вас есть какая-то проблема, можно просто написать нам на info@xabber.com)
