### ISSUE TITLE
don't emulate conversatoins entirely with their poorly crafted feature labels & inane defaults

### ISSUE THREAD

**Issue by BigGiantHeadsHighCommander** [redsolution/xabber-android#835]
I routinely have to explain to people who purport to be friends that disabling the social features of Conversations does not enhance their privacy when talking with friends.  If they are worried about people they don't know don't add them as a contact or use wickr.  "If you're not interested in sharing this with me as I do with you then I'm not interested in talking with you".

Conversations default feature state is inanity.  When I configure the app for a friend I enable all the social share features as I have done on my own devices.  Less that this renders Jabber Texting no more useful than legacy texting (sms).  

The settings header "Privacy" along with descriptors implies [in the minds of most of these people] less privacy with these essential features enabled:

Confirm Messages: let your contacts know when you have received and read their messages

Typing Notifications: let your contacts know when you are writing messages to them

Broadcast Last User Interaction:  let all your contacts know when you use Conversations

^ These are critical to presence and courtesy.

Send button indicates status. 

^ This allows you to respect their time.

Allow message correction.

^ This helps overcome samsung autoINcorrect.

_Availability

Away when screen is off.

I would also  set: DND in silent mode, but my expectation is 

away + DND enabled, screen off:  color for away

away + DVD enabled, screen on: color for DND

In this case however the color is always DND.

_Other

Request message receipt: received messages will be marked with a green tick

ALL of these (except backward function DND availability) ought be enabled by default.

Please don't follow Conversation defaults CRIPPLING SOCIAL use of Jabber Texting.

**Comment by andrewnenakhov** [comment]
Why should we ever emulate ugly as hell clients that even does not show presence or groups normally? lol

**Comment by licaon-kter** [comment]
@andrewnenakhov you've mentioned this (verbatim) on twitter too, what presence is missing exactly from Conversations? What's missing from (current XEP, not future yet not submitted) groups?

**Comment by andrewnenakhov** [comment]
@licaon-kter can you view all online members in a roster group in Conversations?

**Comment by licaon-kter** [comment]
@andrewnenakhov Yes, always seen them.

Maybe you didn't test the app since 2015? Not sure how it was back then...

**Comment by andrewnenakhov** [comment]
Well, [that's](https://xmpp.redsolution.com/upload/4bddf4f264f5c6577f16551f16a0abdf3f7ff84d/1H01ggZM/Screenshot_20190918-020431.png) what I curently see in contacts. Notice that there are two identical contacts of an online account, which is online, but is identical to offline contacts. :-\

**Comment by licaon-kter** [comment]
And you want to _"hide offline"_ (use the menu, press the checkbox) or _"show an online label under online contacts"_ (settings->dynamic tags press the checkbox)?

Or is the fact that _"presence"_ or better said _"online status"_ is not shown by default that's bothering you?

I felt the same for a while (and did not understand the point that Daniel was making), and I do have both _"dynamic tags"_ enabled and _"send button indicates status"_, but using a mobile device I'll be on/off-line as the wind blows or the network type changes, "normie" users are already trained to not care and more importantly: XMPP will deliver every message reliably (yeah yeah 99.999% of the time) in the end when the user is online somewhere.

So, an interested user can enable them, and I do it even for those who use "that app" just because I like this feature, but the rest don't have such worries.

**Comment by andrewnenakhov** [comment]
Oh. It helped. Dynamic tags!! Who could have possibly known that dynamic tags are tied to presence information and roster groups at once! Speaking of UI anti-patterns... 😂 

You see, we clearly understand Daniels approach to hide everything under the hood, like, users don't care, they just want a message delivered. We have a different approach: we believe that users should not be treated as fools and SHOULD see clearly (even if the indication is rather subtle, not distracting a casual user, but visible to an experienced user) what exactly goes on with the connection. When exactly was a message received, down to a second, and not lumping all subsequent messages into one blob.

The 'always online' argument has its merits, sure, but I think we've found a better way to solve this problem: if a user is really offline, but has push notifications enabled, his server posts a special kind of presence that indicates that he's on a mobile device. And a client will display a small mobile phone indicator for such contacts. 

Plus, XMPP stands for Extensible Messaging and Presence Protocol. If you remove presence from it because it's an obsolete concept, you implement XMP protocol, not XMPP.
