### ISSUE TITLE
What data is sent to xabber.com

### ISSUE THREAD

**Issue by licaon-kter** [redsolution/xabber-android#857]
...on every app start?

Why does it still connect even if _"send errors and debug info"_ is disabled?

Why does it try to connect to a broken page at https://crowdfunding.xabber.com ?

Thanks

2.6(557)

**Comment by andrewnenakhov** [comment]
> Why does it still connect even if "send errors and debug info" is disabled?

Because it is neither errors nor debug info. 

In short, xabber does this because we wanted it that way. 

We fetch data about the state of our crowdfunding campaign (which, by the way, performs extremely poor). We planned to increase crowdfunding visibility via a more visible mechanics (thus access to crowdfunding.xabber.com) but ultimately decided against it. In the future, we'll do more native crowdfunding notifications based on XMPP.

**Comment by licaon-kter** [comment]
Where do you show this fetched data?

What data do you transmit to your servers?

What data do your servers log?

How long is this data kept?

**Comment by andrewnenakhov** [comment]
You have our source code and [privacy policy](https://www.xabber.com/policy/) on our xabber.com website, but you ask questions already covered in that document.

In short: we could care less about your precious private data. We don't need it for anything and honestly we're getting annoyed when we have to answer such questions instead of making Xabber better. You are _not_ helping.

**Comment by licaon-kter** [comment]
> We do not store or have any access to user data who do not have Xabber Account or XMPP accounts on our servers.

Answers on 2 out the 4 questions.

The source code? Yes, ~30 references, most to the namespace.
