### ISSUE TITLE
Hangout - Not able to send message

### ISSUE THREAD

**Issue by tbjorheim** [redsolution/xabber-android#878]
I use Xabber with Hangout, and it has worked until lately where I only can receive messages, but not send. When I tries to send, I get an error which says:

`XMPPError: bad-request - modify`
`If set, the 'from' attribute must be set to the user's full JID.`

I use the same account with Pidgin on my computer, and it is setup as a standard XMPP account, and there it works fine.

Is it possible to fix this in Xabber to make it work there too?

**Comment by scottslowe** [comment]
I'm seeing the same behavior with Xabber 2.6.4 (634). I'm able to receive messages, but trying to send messages generates the same error message as the OP.

**Comment by andrewnenakhov** [comment]
Google have officially '[sunsetted](https://gsuiteupdates.googleblog.com/2017/03/updates-in-g-suite-to-streamline-hangouts-and-gmail.html)' XMPP compatibility of Hangouts on June 26, 2017. In years before that, since 2013 they've been quietly removing XMPP features, one by one. 
In that shutdown statement Google did claim that third party xmpp clients will continue to work, and they did, for a time, Xabber included. If it stoped, it's probably because they've changed something Xabber does not understand. 

All things being said, we're not really interested in looking what part of XMPP still functions on a service that went leaps and bounds to distance itself from XMPP and open standards. Hope you understand. We suggest you either move on to using software supplied by Google (Hangouts), or get yourself a real XMPP account. You may register one at xabber.com website. If you need an own domain, we're soon launching an XMPP server with improved features for corporate users.

**Comment by scottslowe** [comment]
Fair enough---mind marking this issue as "Won't Fix" and closing the issue, so that folks know? Thanks!
