### ISSUE TITLE
Contact names missing in contact list

### ISSUE THREAD

**Issue by casperklein** [redsolution/xabber-android#908]
Hi,

after upgrading Prosody from version 0.11.2 to 0.11.3 the contact names are no longer shown in the contact list.
(Switching back from 0.11.3 to 0.11.2 fixes the issue).

I am using Xabber 2.6.4 (634) (last Update from October) from the play store.
However, Xabber Beta 2.6.6.644 (last Update from August) doesn't seem to be affected.

If necessary, I can provide a test account on the server. 

Screenshot:

![Screenshot_20191025-134353_Xabber](https://user-images.githubusercontent.com/590174/67570393-89de0d80-f731-11e9-8d9e-433074372b6c.jpg)

**Comment by andrewnenakhov** [comment]
@casperklein it's strange, i thought we've fixed this issue. It happens when a server puts an empty string in vCard fields. Generally, Xabber uses this order of priorities:
Roster.Nickname > vCard.Nickname > vCard.FirstName + vCard.LastName > XMPP Id

.. and I thought we fixed it in this release, so please do provide us with a test account. Better on email info@xabber.com

**Comment by casperklein** [comment]
With the new released version 2.6.6.644 in the play store, the problem was fixed for me. Thx!
